### ISSUE TITLE
"Unfortunately, BlabberTabber has stopped" while rotating screen during recording.

### ISSUE THREAD

**Issue by cunnie** [blabbertabber/blabbertabber#1]
While rotating the screen back and forth, the application crashed. It appears that there are at least 3 threads:
- 27893-27893 (GUI)
- 27893-28255 (Recorder)
- 27893-28331 (New Recorder)
  Here is the stack trace:

``` log
10-07 10:13:42.065 27893-28255/com.blabbertabber.blabbertabber V/Recorder: getSpeaker(): 0 nextSpeakerChange: 2484
10-07 10:13:42.074 27893-28255/com.blabbertabber.blabbertabber I/Recorder: volume is 3
10-07 10:13:42.079 27893-27893/com.blabbertabber.blabbertabber V/RecordingActivity: mReceiver.onReceive()0, 3
10-07 10:13:42.104 27893-27893/com.blabbertabber.blabbertabber I/RecordingActivity: onPause()
10-07 10:13:42.104 27893-27893/com.blabbertabber.blabbertabber I/RecordingActivity: onStop()
10-07 10:13:42.151 27893-28255/com.blabbertabber.blabbertabber V/Recorder: run() tick
10-07 10:13:42.151 27893-28255/com.blabbertabber.blabbertabber V/Recorder: getSpeaker(): 0 nextSpeakerChange: 2398
10-07 10:13:42.151 27893-28255/com.blabbertabber.blabbertabber I/Recorder: volume is 3
10-07 10:13:42.172 27893-27893/com.blabbertabber.blabbertabber I/RecordingActivity: onCreate()
10-07 10:13:42.173 27893-27893/com.blabbertabber.blabbertabber I/RecordingActivity: onStart()
10-07 10:13:42.175 27893-27893/com.blabbertabber.blabbertabber I/RecordingActivity: bindService() succeeded, mBound: false
10-07 10:13:42.175 27893-27893/com.blabbertabber.blabbertabber I/RecordingActivity: onResume()
10-07 10:13:42.212 27893-28255/com.blabbertabber.blabbertabber V/Recorder: run() tick
10-07 10:13:42.212 27893-28255/com.blabbertabber.blabbertabber V/Recorder: getSpeaker(): 0 nextSpeakerChange: 2337
10-07 10:13:42.212 27893-28255/com.blabbertabber.blabbertabber I/Recorder: volume is 3
10-07 10:13:42.233 27893-27893/com.blabbertabber.blabbertabber I/RecordingService: onDestroy() mThreadRecorder == Thread-21987
10-07 10:13:42.233 27893-27893/com.blabbertabber.blabbertabber I/Recorder: Recorder(): nextSpeakerChange: 9036
10-07 10:13:42.233 27893-27893/com.blabbertabber.blabbertabber I/RecordingService: onCreate()
10-07 10:13:42.234 27893-28331/com.blabbertabber.blabbertabber I/Recorder: run()
10-07 10:13:42.235 27893-28331/com.blabbertabber.blabbertabber I/Recorder: startRecording()
10-07 10:13:42.234 27893-28255/com.blabbertabber.blabbertabber I/Recorder: InterruptedException, return
10-07 10:13:42.235 27893-28255/com.blabbertabber.blabbertabber W/System.err: java.lang.InterruptedException
10-07 10:13:42.235 27893-28255/com.blabbertabber.blabbertabber W/System.err:     at java.lang.Thread.sleep(Native Method)
10-07 10:13:42.235 27893-28255/com.blabbertabber.blabbertabber W/System.err:     at java.lang.Thread.sleep(Thread.java:1031)
10-07 10:13:42.235 27893-28255/com.blabbertabber.blabbertabber W/System.err:     at java.lang.Thread.sleep(Thread.java:985)
10-07 10:13:42.235 27893-28255/com.blabbertabber.blabbertabber W/System.err:     at com.blabbertabber.blabbertabber.Recorder.run(Recorder.java:62)
10-07 10:13:42.236 27893-28255/com.blabbertabber.blabbertabber W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-07 10:13:42.236 27893-28255/com.blabbertabber.blabbertabber I/Recorder: stopRecording()
10-07 10:13:42.236 27893-27893/com.blabbertabber.blabbertabber V/RecordingActivity: mReceiver.onReceive()0, 3
10-07 10:13:42.237 27893-28331/com.blabbertabber.blabbertabber V/BestMicrophone(): getBestMicrophone() Build.MODEL == Nexus 6
10-07 10:13:42.264 27893-27893/com.blabbertabber.blabbertabber V/RecordingActivity: mServerConn.onServiceConnected()
10-07 10:13:42.284 27893-28331/com.blabbertabber.blabbertabber E/MediaRecorder: start failed: -38
10-07 10:13:42.284 27893-28331/com.blabbertabber.blabbertabber E/AndroidRuntime: FATAL EXCEPTION: Thread-21988
10-07 10:13:42.284 27893-28331/com.blabbertabber.blabbertabber E/AndroidRuntime: Process: com.blabbertabber.blabbertabber, PID: 27893
10-07 10:13:42.284 27893-28331/com.blabbertabber.blabbertabber E/AndroidRuntime: java.lang.IllegalStateException
10-07 10:13:42.284 27893-28331/com.blabbertabber.blabbertabber E/AndroidRuntime:     at android.media.MediaRecorder.start(Native Method)
10-07 10:13:42.284 27893-28331/com.blabbertabber.blabbertabber E/AndroidRuntime:     at com.blabbertabber.blabbertabber.DeviceRecorder.startRecording(DeviceRecorder.java:35)
10-07 10:13:42.284 27893-28331/com.blabbertabber.blabbertabber E/AndroidRuntime:     at com.blabbertabber.blabbertabber.Recorder.run(Recorder.java:59)
10-07 10:13:42.284 27893-28331/com.blabbertabber.blabbertabber E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
10-07 10:13:42.299 27893-27893/com.blabbertabber.blabbertabber I/RecordingActivity: onPause()
10-07 10:13:42.342 27893-27893/com.blabbertabber.blabbertabber A/MainActivity: onCreate()
10-07 10:13:42.750 27893-27893/com.blabbertabber.blabbertabber I/RecordingActivity: onStop()
10-07 10:13:42.774 27893-27893/com.blabbertabber.blabbertabber I/RecordingService: onDestroy() mThreadRecorder == Thread-21988
```

**Comment by cunnie** [comment]
Typical log (now that this portion is fixed):

```
10-08 06:39:55.746 20889-21904/com.blabbertabber.blabbertabber E/MediaRecorder: stop failed: -1007
10-08 06:39:55.746 20889-21904/com.blabbertabber.blabbertabber A/Recorder: MediaRecorder.stop() Runtime Exception
```
